[model]
source = "hf-hub"
repo = "onnx-community/yolo26n-ONNX"
revision = "main"

[[model.files]]
file = "onnx/model.onnx"
dest = "yolo26.onnx"

[codegen]
class_name = "Yolo26"
model_file = "yolo26.onnx"
custom_methods = []
